"""Added prof pic & bio columns on User

Revision ID: 55049c1a30ab
Revises: cb11c3ec8913
Create Date: 2021-04-25 08:50:57.726028

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55049c1a30ab'
down_revision = 'cb11c3ec8913'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('bio', sa.String(), nullable=True))
    op.add_column('users', sa.Column('profile_pic_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_pic_path')
    op.drop_column('users', 'bio')
    # ### end Alembic commands ###
